### ISSUE TITLE
hg37 samples

### ISSUE THREAD

**Issue by cccnrc** [broadinstitute/gatk-sv#1]
Hi and thank you very much for this new and clear repository.

I was wondering if this method is somehow suitable for hg37 samples or it is strictly limited to hg38.

Thank you very much in advance!

**Comment by mwalker174** [comment]
Hi @cccnrc, thanks for your request. The short answer is that we don't currently support any of the older references (hg19/GrCh37/b37), but it should work in theory. The pipeline was run on hg19 in the past, but this hasn't been tested in some time. You should only need to replace a number of hg38-specific resource files (eg reference fasta, various sequence dictionary files, interval lists, etc).

**Comment by cccnrc** [comment]
And what about WES samples? Would it theoretically be reliable on them?

**Comment by mwalker174** [comment]
This pipeline will not work on exomes. I would instead recommend the GATK germline CNV caller (see [Terra workspace](https://app.terra.bio/#workspaces/help-gatk/Germline-CNVs-GATK4)).
