### ISSUE TITLE
what is the "wham_include_list_bed_file" : "gs://gcp-public-data--broad-references/hg38/v0/sv-resources/resources/v1/wham_whitelist.bed"

### ISSUE THREAD

**Issue by carolhuaxia** [broadinstitute/gatk-sv#101]
I try to run the Module00a.wdl script. The example of input json file shows that  _"wham_include_list_bed_file" : "gs://gcp-public-data--broad-references/hg38/v0/sv-resources/resources/v1/wham_whitelist.bed"_.  This file is for the  parameter -r of software whamg, which would  guide whamg to make calls in specified intervals after the parameter. I doubt what are the intervals in file _wham_whitelist.bed_. What do these intervals mean?

**Comment by epiercehoffman** [comment]
The parameter `wham_include_list_bed_file` is an optional bed file input with intervals where whamg should make calls. If omitted, whamg will run on the whole genome.

The default file input we use for this (`gs://gcp-public-data--broad-references/hg38/v0/sv-resources/resources/v1/wham_whitelist.bed`) is the inverse of the N-masked regions of the genome (for hg38). So, the intervals describe all regions that are not N-masked.
