### ISSUE TITLE
Manta WDL can break with unexpected cram/bam index extensions

### ISSUE THREAD

**Issue by mwalker174** [broadinstitute/gatk-sv#11]
For example, Manta's configuration script always expects the cram index to be `<cram_path>.crai`, ie ending in `.cram.crai`. Currently, one can pass non-standard index paths, such as in a different directory or lacking `.cram` in the file name. This causes Manta to crash.

This bug may apply to the other callers as well. A fix could use `mv` to ensure the index has a proper path.

**Comment by cwhelan** [comment]
This applies to `.bam` and `.bai` files in Manta as well. It's odd because Manta claimed to have fixed that issue long ago: https://github.com/Illumina/manta/issues/14. It might be worth investigating whether this is something particular to our setup somehow.

**Comment by cwhelan** [comment]
Closed via https://github.com/broadinstitute/gatk-sv/pull/54
