### ISSUE TITLE
No coercion from '4' of type java.lang.integer to string WDL

### ISSUE THREAD

**Issue by NewOrange** [broadinstitute/gatk-sv#12]
### Description 
I am trying to test the GATKSVPipelineBatch.wdl with GATKSVPipelineBatch.ref_panel_1kg.json, and meet this log.
**logs**:
```
No coercion from '4' of type java.lang.integer to string WDL 
```
Is there any way to solve this problem?
Thank you very much for discussing this with me.

**Comment by mwalker174** [comment]
Hello @NewOrange, can you please provide some more details including: the commands you used to set up and launch the workflow, version of cromwell, whether you modified the json, and what log produced the error?

**Comment by NewOrange** [comment]
Hello, @mwalker174 ，I am sorry that my description is not detailed enough.
The version of cromwell I used is 51, and I docker pull images  to my local laptop declared in the json file，except melt.
The version of java I used is 1.8.0.
Then, I just choose one sample labeled HG00096，and modified the json to fit the file path on my local laptop，change the value of "GATKSVPipelineBatch.use_melt" to "false".
The commands I used to set up and launch the workflow is:
```
cromshell submit wdl/GATKSVPipelineBatch.wdl GATKSVPipelineBatch.my_run.json cromwell_config.json wdl/dep.zip
```
Then , I find the log like this:
![image](https://user-images.githubusercontent.com/10742012/86302771-55194300-bc3c-11ea-9d7b-b7ead92c31c7.png)
When I try to use samtools， I just assign an integer value to this parameter.
```
samtools view \\
     -@ INT
```
Is there any way to solve this problem?

**Comment by NewOrange** [comment]
```
$ java -version
openjdk version "1.8.0_252"
OpenJDK Runtime Environment (build 1.8.0_252-8u252-b09-1ubuntu1-b09)
OpenJDK 64-Bit Server VM (build 25.252-b09, mixed mode)
```
cromwell_config.json: 
```
{
    "backend": "LocalWithDocker"
}
```

**Comment by mwalker174** [comment]
Thanks for the details, @NewOrange. I'm not sure what is causing this error and I'm not able to reproduce it on my laptop. I would double-check that the CramToBam WDL hasn't been accidentally modified.

That said, I would not recommend trying to run this pipeline locally. There are a number of tasks that require GCS functionality and will only work in the cloud. And, practically speaking, the full pipeline would probably take months to run on a single machine.

**Comment by NewOrange** [comment]
Thank you very much for your reply, @mwalker174 .
No matter whether there is a problem with **CramToBam.WDL** please contact me again. 
I'm sorry, but I still have two questions.
1. I just select one sample with the ID of HG00096 to run this pipeline locally without melt. I'm not sure whether I can run the GATKSVPipelineBatch.wdl **without melt**.
2. As you said,there are a number of tasks that require GCS functionality. If I want to run the GATKSVPipelineBatch.wdl with the ID of HG00096 on goole cloud，I have no idea about how to choose the **parameters of CPU, memory, hard disk**.
Do you have some good suggestions about this?

**Comment by mwalker174** [comment]
The `GATKSVPipelineBatch` WDL can be run without melt. However, this workflow will not work with 1 sample - you need at least ~100 samples (see README file). Instead you should use the `GATKSVPipelineSingleSample` WDL.

**Comment by NewOrange** [comment]
Hi, @mwalker174 , thank you so much,
When I switched to another machine, this problem no longer occurred.This problem may be related to my environment configuration.
