### ISSUE TITLE
KeyError: 'Required INFO field CHR2 not found in file 100001.wham.vcf.gz' KeyError: 'Required INFO field STRANDS not found in file 100001.delly.vcf.gz'

### ISSUE THREAD

**Issue by jingydz** [broadinstitute/gatk-sv#128]

**Comment by jingydz** [comment]
Module01 PESRClustering.wdl

My json file
`$ cat PESRClustering.json
{
  "ClusterPESR.frac": "0.1",
  "ClusterPESR.flags": "--preserve-ids",
  "ClusterPESR.exclude_list": "/home/resource/hg38_v0_sv-resources_resources_v1_GRCh38_Nmask.sorted.bed.gz",
  "ClusterPESR.dist": "300",
  "ClusterPESR.algorithm": "wham",
  "ClusterPESR.svsize": "0",
  "ClusterPESR.batch": "PESRtest",
  "ClusterPESR.vcfs": [
  "/home/Wham/100001.wham.vcf.gz",
  "/home/Wham/100002.wham.vcf.gz",
  "/home/Wham/100003.wham.vcf.gz",
  "/home/Wham/100004.wham.vcf.gz"
  ],
  "ClusterPESR.svtypes": "DEL,DUP,INV,BND,INS",
  "ClusterPESR.contigs": "/home/gatk_sv/resource/hg38_v0_sv-resources_resources_v1_contig.fai"
}
`
The error logfile:
`Job ClusterPESR.VCFCluster:10:1 exited with return code 1 which has not been declared as a valid return code. See 'continueOnReturnCode' runtime attribute for more details.
Check the content of stderr for potential additional information: /home/cromwell-executions/ClusterPESR/5ffc1441-440a-4bb0-a329-3207b7816a50/call-VCFCluster/shard-10/execution/stderr.
 [First 300 bytes]:sort -k1,1V -k2,2n
Traceback (most recent call last):
  File "/home/software/anaconda3/envs/cromwell/bin/svtk", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/work/SV/gnomad_sv_code/svtk/scripts/svtk", line 67, in <module>
    main()
  File "/home/w
`
```
cat /home/cromwell-executions/ClusterPESR/5ffc1441-440a-4bb0-a329-3207b7816a50/call-VCFCluster/shard-10/execution/stderr
KeyError: 'Required INFO field CHR2 not found in file 100001.wham.vcf.gz‘
```
And I noticed that the INFO column of the VCF file from running the Delly software contains CHR2.
So I modified the json file.
`$ cat PESRClustering.json
{
  "ClusterPESR.frac": "0.1",
  "ClusterPESR.flags": "--preserve-ids",
  "ClusterPESR.exclude_list": "/home/resource/hg38_v0_sv-resources_resources_v1_GRCh38_Nmask.sorted.bed.gz",
  "ClusterPESR.dist": "300",
  "ClusterPESR.algorithm": "delly",
  "ClusterPESR.svsize": "0",
  "ClusterPESR.batch": "PESRtest",
  "ClusterPESR.vcfs": [
  "/home/Delly/100001.delly.vcf.gz",
  "/home/Delly/100002.delly.vcf.gz",
  "/home/Delly/100003.delly.vcf.gz",
  "/home/Delly/100004.delly.vcf.gz"
  ],
  "ClusterPESR.svtypes": "DEL,DUP,INV,BND,INS",
  "ClusterPESR.contigs": "/home/gatk_sv/resource/hg38_v0_sv-resources_resources_v1_contig.fai"
}
`
However, I got a similar error.
KeyError: 'Required INFO field STRANDS not found in file 100001.delly.vcf.gz'

My command is
`
java -Dconfig.file=torque.conf -jar /home/Tools/bin/cromwell-54.jar run PESRClustering.wdl -i PESRClustering.json >PESRClustering.log & disown
`

I noticed the svfile.py file.
The INFO column is required to contain CHR2 and Strands information.
![image](https://user-images.githubusercontent.com/45711930/110239598-c905ab00-7f82-11eb-85bc-4d7faf6cad34.png)
![image](https://user-images.githubusercontent.com/45711930/110239666-0c601980-7f83-11eb-9d59-5e18945ef6cc.png)
What should I do if my VCF files do not include CHR2 and Strands?

Thanks in advance!

**Comment by leipzig** [comment]
@jingydz did you solve this

**Comment by cwhelan** [comment]
@leipzig  We didn't respond to this because it was closed right away but the answer is that input VCFs from the raw callers (Manta, Wham, Delly) have these fields added by the `StandardizeVCFs`workflow that's called by the `GatherBatchEvidence` -> `PreprocessPESR` workflows. Downstream workflows expect that all input VCFs have been standardized to the format expected by the pipeline by this workflow, which runs `svtk standardize` on each input VCF.
