### ISSUE TITLE
svtk pe-test: error: unrecognized arguments: --common

### ISSUE THREAD

**Issue by jingydz** [broadinstitute/gatk-sv#131]
Hi,
 I am testing Module02. There is a submodule, named PETest.wdl, and I have the following problem in testing.
https://github.com/broadinstitute/gatk-sv/blob/master/wdl/PETestChromosome.wdl#L193
 ` String common_arg = if common_model then "--common" else ""`
https://github.com/broadinstitute/gatk-sv/blob/master/wdl/PETestChromosome.wdl#L244
`svtk pe-test -o ~{window} ~{common_arg} --medianfile ~{medianfile} --samples ~{include_list} ~{vcf} local.PE.txt.gz ~{prefix}.stats`

`$ svtk pe-test -o 1000 --index PE.txt.gz.tbi --common --medianfile /home/luohx/work/SV/own_execute/sv_script/jjzhang/Module02/cromwell-executions/PETest/2df715b8-e2a8-40fb-ab7a-5e964f79f14e/call-PETestAutosome/shard-20/PETestChromosome/b57d219b-c6cb-41c5-90f7-9d2b58438c23/call-PETestAutosomeCommon/shard-0/inputs/1263417245/test_small_medianCov.transposed.bed --samples /home/luohx/work/SV/own_execute/sv_script/jjzhang/Module02/cromwell-executions/PETest/2df715b8-e2a8-40fb-ab7a-5e964f79f14e/call-PETestAutosome/shard-20/PETestChromosome/b57d219b-c6cb-41c5-90f7-9d2b58438c23/call-PETestAutosomeCommon/shard-0/inputs/1767322580/samples.list /home/luohx/work/SV/own_execute/sv_script/jjzhang/Module02/cromwell-executions/PETest/2df715b8-e2a8-40fb-ab7a-5e964f79f14e/call-PETestAutosome/shard-20/PETestChromosome/b57d219b-c6cb-41c5-90f7-9d2b58438c23/call-PETestAutosomeCommon/shard-0/inputs/174181538/common_SVs.vcf.gz PE.txt.gz peTEST.delly.split.0000.vcf.gz.stats
usage: svtk pe-test [-h] [-o WINDOW_OUT] [-i WINDOW_IN] [-b BACKGROUND] [-s SAMPLES] [--index INDEX]
                    [--medianfile MEDIANFILE] [--log]
                    vcf disc fout
svtk pe-test: error: unrecognized arguments: --common
`

**Comment by cwhelan** [comment]
Hi, what version of `svtk` are you using? All versions built from this repository should accept the `--common` argument. If you are able to use docker, I'd recommend running the `sv_pipeline_docker` image referenced in `input_values/dockers.json`.

**Comment by jingydz** [comment]
> Hi, what version of `svtk` are you using? All versions built from this repository should accept the `--common` argument. If you are able to use docker, I'd recommend running the `sv_pipeline_docker` image referenced in `input_values/dockers.json`.

Thank you. I eventually found out that I had been using version 0.1 svtk(https://github.com/talkowski-lab/svtk).  And then I got the "--common" parameter when I updated to the latest version(0.13 svtk).
