### ISSUE TITLE
Haplotype Caller GVCF - Is GenotypeGVCF Required?

### ISSUE THREAD

**Issue by hevmarriott** [broadinstitute/gatk-sv#134]
Hi there, 

For module 00c input (GVCFs produced by Haplotype Caller) to calculate the BAF, is the GVCF produced by Haplotype Caller sufficient, or would you also recommend putting the GVCFs through GenotypeGVCF before adding them as input for the module. 

Many thanks, 

Heather

**Comment by cwhelan** [comment]
If you are using the `gvcfs` input for `Module00c.wdl`, the GVCFs produced by HaplotypeCaller are the right input files (rather than the output of GenotypeGVCFs).
