### ISSUE TITLE
GCloud statement

### ISSUE THREAD

**Issue by henriqueribeiro** [broadinstitute/gatk-sv#141]
### Affected module(s) or script(s)
- MakeBincovMatrix

### Affected version(s)
- [x] Latest public release version [version?]
- [ ] Latest master branch as of [date of test?]

### Description 
Is this line needed in the task?
https://github.com/broadinstitute/gatk-sv/blob/b8dbf083895c0623227050bda7d26b26e54fba5b/wdl/MakeBincovMatrix.wdl#L263

I'm using the AWS backend and, as expected, it fails at this line.

**Comment by jingydz** [comment]
I've had this problem before, but just delete the sentence and it will work.

**Comment by mwalker174** [comment]
We still use this command in a few places, most notably CramToBam (work around by enabling requester pays option). Closing, however, since do not have plans at this time to support AWS.
