### ISSUE TITLE
SvtkVcfCluster: Too many open files

### ISSUE THREAD

**Issue by henriqueribeiro** [broadinstitute/gatk-sv#142]
### Affected module(s) or script(s)
SvtkVcfCluster

### Affected version(s)
- [ ] Latest public release version [version?]
- [x] Latest master branch as of 05/04/2021

### Description 
I'm running `GATKSVPipelineBatch` wdl and in Module0506 I get the following error in `SvtkVcfCluster` task:
```
[E::hts_open_format] Failed to open file temp/01022.bcf
Could not read temp/01022.bcf: Too many open files
```
I also attach the complete log file.
[log-events-result.log](https://github.com/broadinstitute/gatk-sv/files/6264996/log-events-result.log)

This is a scatter task and only one is failing.

#### Steps to reproduce
Run GATKSVPipelineBatch.wdl with AWS Backend

**Comment by epiercehoffman** [comment]
When I searched for your error message, I found this [samtools ticket](https://github.com/samtools/samtools/issues/603), which recommends increasing the memory for the sort task. The easiest way to do that for this workflow would be to increase the memory for the task with the runtime attribute override variable `runtime_override_svtk_vcf_cluster` in Module0506. Unfortunately, this would apply to all shards. 

The memory for the sort command is determined dynamically for this task. We haven't encountered this error regularly before, but I will leave the issue open for now as a record in case this becomes an ongoing issue and we need to update the memory model.

**Comment by henriqueribeiro** [comment]
Hey! I did a PR on cromwell to accept `ulimits` attribute and pass it to docker on AWS backend. Now it's possible to define the maximum number of opened files. I already tried running the task again and it's working fine. I will close this for now. Thank you
