### ISSUE TITLE
[module02] GATK_JAR: unbound variable

### ISSUE THREAD

**Issue by jingydz** [broadinstitute/gatk-sv#144]
[2021-04-09 17:48:44,44] [info] WorkflowManagerActor Workflow dc958273-32c4-4dbe-aceb-61be4239f0ea failed (during ExecutingWorkflowState): Job BAFTestChromosome.BAFTest:
1:1 exited with return code 1 which has not been declared as a valid return code. See 'continueOnReturnCode' runtime attribute for more details.
Check the content of stderr for potential additional information: /home/luohx/work/SV/own_execute/sv_script/jjzhang/M02pipe_2021.4.9/cromwell-executions/Module02/dc958273-32c4-4dbe-aceb-61be4239f0ea/call-BAFTest/shard-4/BAFTest/d6eee583-2e65-4499-95c3-4a248275f930/call-BAFTestAutosome/shard-16/BAFTestChromosome/16d50b09-b54a-4cc5-8b60-1b953ba42816/call-BAFTest/shard-1/execution/stderr.
 [First 300 bytes]:/opt/gridview//pbs/dispatcher/mom_priv/jobs/415451.admin.SC: line 34: GATK_JAR: unbound variable

Hi, I want to know what the GATK_JAR variable represents in the WDL script ?
https://github.com/broadinstitute/gatk-sv/blob/master/wdl/BAFTestChromosome.wdl#L128
https://github.com/broadinstitute/gatk-sv/blob/master/wdl/PETestChromosome.wdl#L232
https://github.com/broadinstitute/gatk-sv/blob/master/wdl/RDTestChromosome.wdl#L184
https://github.com/broadinstitute/gatk-sv/blob/master/wdl/SRTestChromosome.wdl#L232

**Comment by jingydz** [comment]
![image](https://user-images.githubusercontent.com/45711930/114166622-90316b00-9960-11eb-8984-f58a5d444439.png)

**Comment by epiercehoffman** [comment]
This variable is defined [here](https://github.com/broadinstitute/gatk-sv/blob/cc4842e51bf069d6bf32aa3f3752b81113d1b07b/dockerfiles/sv-base/Dockerfile#L15) in the `sv_base` docker and provides the location of the GATK jar within the docker container. The pipeline is designed to be run with the provided docker containers, which are publicly available on Google Container Repository (find the latest images [here](https://github.com/broadinstitute/gatk-sv/blob/master/input_values/dockers.json)).
