### ISSUE TITLE
gCNV Training Problem

### ISSUE THREAD

**Issue by ghzhaole** [broadinstitute/gatk-sv#151]
### Problem report

Hi，when running gCNV Training module with a batch of samples (364 samples)，it usually takes a large disk space for storage (nearly 100 samples with 20T). It is too space comsuming to run remaining samples. I wonder is it the common situation? Or is there any step I've missed?

*The batch of samples are produced followed QC and batching steps in the paper.

Any help is greatly appreciated!

----

**Comment by mwalker174** [comment]
For training, we recommend using a subset of up to 100 samples randomly selected from the batch. Recently #149 made this easy to do.
