### ISSUE TITLE
Reduce sv-pipeline docker image sizes

### ISSUE THREAD

**Issue by cwhelan** [broadinstitute/gatk-sv#162]
We should find ways to reduce the sizes of our sv-pipeline docker images. 

My most recent builds of sv-pipeline-base, sv-pipeline, and sv-pipeline-rdtest were 3.56GB, 4.33GB, and 4.57GB, respectively.

It seems likely that conda dependency lists have changed and brought in more dependent packages over time. 

@TedBrookings suggests looking into the approach outlined here to prevent this from happening.

**Comment by TedBrookings** [comment]
I'm guessing you meant to link this: https://pythonspeed.com/articles/conda-dependency-management/

**Comment by TedBrookings** [comment]
Closing this now, since several PRs have come in to make the docker images much leaner.
