### ISSUE TITLE
Using MELT directly with CRAM files

### ISSUE THREAD

**Issue by pdiakumis** [broadinstitute/gatk-sv#165]
Thanks all for your awesome work on this pipeline.
I was wondering if you've explored using MELT with CRAMs as input, instead of pre-converting to BAMs?
MELT theoretically supports CRAMs since v2.1.6 (July 2018).

**Comment by mwalker174** [comment]
The pipeline currently uses v2.0.5, so I don't believe that would work right now. FWIW, some of the other callers do support CRAM, but we decided to use BAM because it reduces run time.
