### ISSUE TITLE
MELT.melt_standard_vcf_header

### ISSUE THREAD

**Issue by cccnrc** [broadinstitute/gatk-sv#19]
Hi guys, quick question. I downloaded MELT and made docker. How can I generate such `MELT.melt_standard_vcf_header` file?

**Comment by cwhelan** [comment]
Hi @cccnrc , I've made a copy of this file publicly available at the GCS URL `gs://gatk-sv-resources-public/hg38/v0/sv-resources/resources/v1/melt_standard_vcf_header.txt`
