### ISSUE TITLE
Cromwell independent usage? Easier usage?

### ISSUE THREAD

**Issue by mvelinder** [broadinstitute/gatk-sv#195]
Would it be possible to have a usage that does not require Cromwell and submitting jobs to a remote server? 

It'd be much easier to use the tool (on AWS and institutional compute clusters) if it could be run as a typical Docker/Singularity image (similar to DeepVariant and other modern tools).

**Comment by mvelinder** [comment]
I think I've successfully built the Docker images using the `build_docker.py` file. What is the recommended usage from here?

**Comment by mvelinder** [comment]
Is there any documentation for using gatk-sv built from Docker images?

**Comment by cwhelan** [comment]
Hi -- you will need to run the pipeline using Cromwell (or another compliant WDL execution engine, although we only have experience with Cromwell). I'd recommend reading through the Cromwell documentation to figure the ways in which you can configure Cromwell to run workflows. Depending on the backend you set up, Cromwell can run workflows using cloud VMs, with HPC (SGE, LSF, ...) backends, or locally (we only officially support running with a google cloud backend for this workflow, but other groups have successfully run some of the pipelines on HPC backends). Once you have figured out your Cromwell configuration, you'll want to choose the WDL to run (`GATKSVPipelineBatch.wdl` or `GATKSVPipelineSingleSample.wdl`) and prepare an input JSON as documented in the README.

**Comment by mvelinder** [comment]
So there's no way to use it without setting up an entire backend job submission system?

**Comment by cwhelan** [comment]
The pipeline is written in WDL so you will need a WDL execution engine to run it. The docker build process (depending on how you ran it) creates quite a few different docker images, which are used at different stages in the pipeline. The WDL pipeline definitions describe what commands get run using which docker images and in what order. Much of the logic of the pipeline is encoded in the WDL itself, so it's necessary to use some sort of WDL execution engine (whether Cromwell or something else) to run it. 

If you don't want to install a WDL workflow engine and are amenable to running things in the cloud, then depending on your use case (number of samples, etc) you might be able to use the preconfigured workspaces for the pipeline on the Terra platform, which executes WDL workflows using Cromwell on the Google Cloud Platform. For example, the single sample version of the pipeline is available as a featured workspace here: https://app.terra.bio/#workspaces/help-gatk/GATK-Structural-Variants-Single-Sample

**Comment by mvelinder** [comment]
Thanks @cwhelan ! I'll explore options
