### ISSUE TITLE
Module00c space comsuming

### ISSUE THREAD

**Issue by ghzhaole** [broadinstitute/gatk-sv#199]
# Problem Report
Hi，when running Module00c with a batch of samples (364 samples)，it usually takes more disk space than gCNV Training(more than 20T/batch). It is too space comsuming to finish the process. Is there any solution?

Any help is greatly appreciated!

**Comment by mwalker174** [comment]
That sounds rather high. Is the 20T for a single run or is that accumulated over multiple attempts of the same batch?

If you are running on GCP with a Cromwell server, we recommend using an execution bucket with [time-to-live](https://cloud.google.com/storage/docs/lifecycle) on all objects, which will automatically delete files after a set time has elapsed.

**Comment by mwalker174** [comment]
Intermediate file storage is a general issue we need to work on. For GatherBatchEvidence (formerly 00c), I'd prefer to put this off, as we're planning substantial changes in the near future.
