### ISSUE TITLE
GatherSampleEvidence description needs update

### ISSUE THREAD

**Issue by sph17** [broadinstitute/gatk-sv#246]
In GatherSampleEvidence readme section, BAF is listed as an output, but this is actually performed in GatherBatchEvidence. BAF file needs to be removed from output list.

> GatherSampleEvidence
> Formerly Module00a
> 
> Runs raw evidence collection on each sample with the following SV callers: Manta, Wham, and/or MELT. Delly can be enabled but is no longer officially supported. For guidance on pre-filtering prior to GatherSampleEvidence, refer to the Sample Exclusion section.
> 
> Note: a list of sample IDs must be provided. Refer to the sample ID requirements for specifications of allowable sample IDs. IDs that do not meet these requirements may cause errors.
> 
> Inputs:
> Per-sample BAM or CRAM files aligned to hg38. Index files (.bai) must be provided if using BAMs.
> 
> Outputs:
> Caller VCFs (Delly, Manta, MELT, and/or Wham)
> Binned read counts file
> Split reads (SR) file
> Discordant read pairs (PE) file
> _**B-allele fraction (BAF) file**_
>

**Comment by epiercehoffman** [comment]
Addressed by #248
