### ISSUE TITLE
Deprecate Delly support

### ISSUE THREAD

**Issue by epiercehoffman** [broadinstitute/gatk-sv#249]
We are no longer using Delly for our most recent cohorts, and we have observed an overabundance of Delly calls that make processing difficult and resource-intensive. We should remove support for Delly and references to Delly throughout the pipeline to avoid confusion for users. This would involve changes (mostly removing inputs/outputs) to:
* GatherSampleEvidence and GatherSampleEvidenceBatch
* EvidenceQC
* GatherBatchEvidence
* ClusterBatch
* GenerateBatchMetrics
* FilterBatch and subworkflows
* Metrics workflows for the above steps
* Remove Delly docker
* Remove Delly WDL

**Comment by mwalker174** [comment]
Addressed in #376
