### ISSUE TITLE
Request for the exemplary output.

### ISSUE THREAD

**Issue by June3billion** [broadinstitute/gatk-sv#266]
### Module(s) or script(s) involved
Cohort mode (GATKSVPipelineBatch.wdl)
Single-sample mode (GATKSVPipelineSingleSample.wdl)

### Description
Dear GATK-SV developers

Would you upload the exemplary outputs for each mode?
(I want to compare with my output to check whether gatk-sv worked correctly, in terms of format and contents.)
Or, It would be helpful if I can see some output from the gatk-sv pipeline
(Is this file have the same format as the gatk-sv output?: https://storage.googleapis.com/gcp-public-data--gnomad/papers/2019-sv/gnomad_v2.1_sv.sites.vcf.gz)

**Comment by epiercehoffman** [comment]
There have been a few minor changes compared to the gnomAD-v2 SV VCF. You can view a publicly-available, relatively recent example of the VCF output from MakeCohortVcf here: `gs://gatk-sv-resources-public/hg38/v0/sv-resources/ref-panel/1KG/v2/ref_panel_1kg_v2.cleaned.vcf.gz`. This path is from our reference panel that uses 1000 Genomes High-Coverage samples, and you can find related file paths under `/input_values/ref_panel_1kg_v2.json`. 

You can also view the files in the featured workspace for the GATK-SV single-sample pipeline, which is here: https://app.terra.bio/#workspaces/help-gatk/GATK-Structural-Variants-Single-Sample. For example, the final annotated VCF is here: `gs://fc-bcde7821-e293-4efc-9c18-f2af58b28ff6/6602a4ce-84c9-4fea-bae2-2e5c18c85bdb/GATKSVPipelineSingleSample/54d264c5-3256-4556-b1f4-27086be95bbc/call-FinalVCFCleanup/NA12878.pruned_wAFs.annotated.final_cleanup.vcf.gz`. Note that there are a few differences in the final VCF format output by the single-sample pipeline, including changes to END tags and the way BNDs and CTX events are represented.

We are also working to switch over to public test data, after which we will have publicly-available inputs and outputs for each step of the pipeline, not just the final output. The relevant issue is #10.
