### ISSUE TITLE
Update dockers with latest release of tools using log4j

### ISSUE THREAD

**Issue by epiercehoffman** [broadinstitute/gatk-sv#275]
We use several tools that have made new releases to update log4j for a security patch. Due to the way GATK-SV is run, the level of risk posed by this security issue is likely to be very low; however, we should still update our dockers to use the latest version of any tools that use log4j. 

Tools using log4j in our pipeline appear to be: GATK, Picard

Dockers to update:
* gatk_docker
* gatk_docker_pesr_override - remove as duplicate of gatk_docker?
* genomes_in_the_cloud_docker (Picard) - is there an existing image we can reference?
* condense_counts_docker (GATK branch) - should attempt to merge this tool so we can use the regular GATK docker for this. Otherwise, will need to rebase or update the branch before rebuilding the docker to get the log4j update
* sv_base_docker and above

**Comment by mwalker174** [comment]
Closing since the main gatk dockers are updated, so this is basically a duplicate of #324
