### ISSUE TITLE
Example cromwell_config.json

### ISSUE THREAD

**Issue by szitenberg** [broadinstitute/gatk-sv#278]
Would it be possible to include or point to an example `cromwell_config.json` file?

**Comment by epiercehoffman** [comment]
Hi, we do link to the [cromwell documentation on workflow options](https://cromwell.readthedocs.io/en/stable/wf_options/Overview/) in the [Quickstart > Execution](https://github.com/broadinstitute/gatk-sv#execution) section of our README, and that includes an example cromwell config JSON. For GCP, an additional example JSON from the cromwell documentation is [here](https://cromwell.readthedocs.io/en/stable/wf_options/Google/#example).
