### ISSUE TITLE
GatherBatchEvidenceMetrics_PEMetrics task failing

### ISSUE THREAD

**Issue by henriqueribeiro** [broadinstitute/gatk-sv#287]
### Affected module(s) or script(s)
GatherBatchEvidenceMetrics_PEMetrics

### Affected version(s)
- [x] Latest public release version [version?]
- [ ] Latest master branch as of [date of test?]

### Description 
I got an error while running module `GatherBatchEvidenceMetrics_PEMetrics`. Here is the stacktrace:

```
Traceback (most recent call last):
  File "/opt/conda/bin/svtest", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/opt/svtest/scripts/svtest", line 53, in <module>
    main()
  File "/opt/svtest/scripts/svtest", line 50, in main
    getattr(cli, command)(sys.argv[2:])
  File "/opt/svtest/svtest/cli/pe_file.py", line 44, in main
    metrics = get_metrics(fpe, args.sample_list)
  File "/opt/svtest/svtest/cli/pe_file.py", line 62, in get_metrics
    test_record(tokens, samples_set)
  File "/opt/svtest/svtest/cli/pe_file.py", line 92, in test_record
    tu.test_iterable_size(columns, 7)
  File "/opt/svtest/svtest/utils/TestUtils.py", line 30, in test_iterable_size
    (size, len(iterable), str(iterable)))
ValueError: Expected 7 values but found 10 in: ['chr2', '32916486', '+', 'chr13chr2', '32916486', '+', 'chr13', '92720139', '-', 'NA11894']
```
As you know this tasks is running `svtest pe-file ~{pe_file} ~{samples_list} > ~{prefix}.pe-file.tsv` command, where the `pe_file` is `ref_panel_1kg_v2.PE.txt.gz`.

I extracted that file and noticed that the problem seems to be in line 299701698. Below is the content of the file from that line and the 3 previous ones:

```
line: 299701695 -> ['chr2', '32916486', '+', 'chr13', '83766964', '+', 'NA11894']
line: 299701696 -> ['chr2', '32916486', '+', 'chr13', '83798511', '-', 'NA11894']
line: 299701697 -> ['chr2', '32916486', '+', 'chr13', '83803983', '+', 'NA11894']
line: 299701698 -> ['chr2', '32916486', '+', 'chr13chr2', '32916486', '+', 'chr13', '92720139', '-', 'NA11894']
```

As you can see, the contents of line 299701698 is different from the others. Did this happened to someone before? Can you please give me some hints on what is wrong and how I can fix it?

#### Steps to reproduce
Not sure how to reproduce it since it's the first time this happens

Thanks

**Comment by epiercehoffman** [comment]
I haven't had a chance to look into this in more detail, but in the mean time I wanted to let you know that the outputs of GatherBatchEvidenceMetrics are for debugging purposes and are not used in subsequent steps of the pipeline. To disable this subworkflow, you can run GatherBatchEvidence with the input `run_module_metrics` set to `false`. This also applies to other steps of the pipeline and their corresponding metrics subworkflows.

**Comment by mwalker174** [comment]
We saw this occasionally when running gnomAD as well.  My best guess is this happens in `MergeEvidenceFilesByContig` in `BatchEvidenceMerging.wdl`. There could be an issue in the version of `tabix` we use that causes some newline characters to be dropped. I'm currently generating a fresh reference panel run and will be sure to check for this.

**Comment by mwalker174** [comment]
This does seem to have been addressed, probably by avoiding the use of remote bucket access with tabix, as we haven't encountered it in some time. Closing until it comes up again.
