### ISSUE TITLE
Somatic SV detection

### ISSUE THREAD

**Issue by chadohyeon** [broadinstitute/gatk-sv#33]
Hello, 

I've read the published gnomAD-SV paper and I'd like to use it for my project. 
I currently have two projects, one is to detect germline SV from simplex family WGS and
the other one is to detect somatic SV from paired tissues WGS.

For the germline one, I think I can apply this whole workflow straightforwardly.
However, I think I should redesign or optimize the GATK-SV workflow for somatic SV calling.

Which jobs would be recommended if I want to optimize it for somatic SV calling? (e.g., adjusting some parameters)

Thank you for reading this

Dohyeon

**Comment by mwalker174** [comment]
Hi @chadohyeon, this pipeline was not designed for somatic calling, so we really would not advise it.
