### ISSUE TITLE
CondenseReadCounts is not a function of GATK v4

### ISSUE THREAD

**Issue by wanpinglee** [broadinstitute/gatk-sv#35]
### Affected module(s) or script(s)
Module00c.wdl/CollectCoverage.wdl/CondenseReadCounts

### Affected version(s)
15c9be70bb07389c8c8078ce07ce69dae536c853

### Description 
CondenseReadCounts is not a function of GATK v4.
Have tried GATK 4.1.2 and 4.1.8.

**Comment by mwalker174** [comment]
This tool was never merged into GATK master (see https://github.com/broadinstitute/gatk/pull/5707). I'll keep this ticket open since that should be a goal.

If you do need to use this tool, you can find it in the docker `gatksv/gatk:condensecounts-7396ae99aaab07e29c92b509a6515508fbe68158`.

**Comment by mwalker174** [comment]
Addressed in #370
