### ISSUE TITLE
Add miniwdl validation for WDLs

### ISSUE THREAD

**Issue by mwalker174** [broadinstitute/gatk-sv#368]

**Comment by VJalili** [comment]
Addressed in https://github.com/broadinstitute/gatk-sv/pull/385, https://github.com/broadinstitute/gatk-sv/pull/402, https://github.com/broadinstitute/gatk-sv/pull/439, https://github.com/broadinstitute/gatk-sv/pull/448, and https://github.com/broadinstitute/gatk-sv/pull/450.
