### ISSUE TITLE
How to make a 1kg_ref_panel_v1.ped?

### ISSUE THREAD

**Issue by NewOrange** [broadinstitute/gatk-sv#37]
### Description 
Recently, I just want to use ：gs://gcp-public-data--broad-references/hg38/v0/sv-resources/ref-panel/1KG/v1/ped/1kg_ref_panel_v1.ped.
The content is as follows:
```
HG00129 HG00129 0 0 1 0
HG00140 HG00140 0 0 1 0
```
I want to make a file like this for my own dataset, but I have no idea about the meaning of these columns. How do I understand the meaning of these columns?
***
Thank you very much.

**Comment by cwhelan** [comment]
Hi @NewOrange, the ped file is in PLINK pedigree format: https://zzz.bwh.harvard.edu/plink/data.shtml#ped

The important columns that the pipeline looks at are IID (individual ID) and sex.

If you are trying to run the single sample pipeline, you shouldn't need to create a ped file yourself as long as you're using the 1000 Genomes reference panel.

**Comment by NewOrange** [comment]
Hii @cwhelan, thank you so much.
I am tring to run the batch pipeline with two real sequencing data. I’m not sure if it can run successfully, when not using the cloud resource.
Just want to try and kown more about the batch pipeline.

**Comment by cwhelan** [comment]
To run in Batch mode you'll need to provide inputs for your data similar to what's in `GATKSVPipelineBatch.ref_panel_1kg.json`, including a ped file. You'd also need to train a gCNV model with the TrainGCNV workflow. 

We recommend running on batch sizes of 100-500 samples, so if you mean two samples, that wouldn't be enough. If that's the case, I'd recommend running the single sample pipeline (with the 1000 genomes reference panel files) on each sample individually.
