### ISSUE TITLE
Error with END2 coordinates for dispersed duplications

### ISSUE THREAD

**Issue by alsanju** [broadinstitute/gatk-sv#377]
### Affected module(s) or script(s)
Suspected svtk resolve

### Description 
Dispersed duplications have the insertion point as `END2`, but this field should correspond to the end of the duplicated interval.

#### Actual behavior
The following SV is an example of a dispersed duplication with wrong `END2` coordinates:

```
chr10	89259888	phase2_CPX_chr10_71	N	<CPX>	1	BOTHSIDES_SUPPORT	ALGORITHMS=manta;CHR2=chr22;CPX_INTERVALS=DUP_chr22:29481383-29481712;CPX_TYPE=dDUP;END=89259888;END2=89259888;EVIDENCE=PE,SR;SOURCE=DUP_chr22:29481383-29481712;SVLEN=329;SVTYPE=CPX;PROTEIN_CODING__DUP_PARTIAL=NEFH;NONCODING_SPAN=DNase;NONCODING_BREAKPOINT=Tommerup_TADanno;AN=4938;AC=1;AF=0.000203;N_BI_GENOS=2469;N_HOMREF=2468;N_HET=1;N_HOMALT=0;FREQ_HOMREF=0.999595;FREQ_HET=0.000405022;FREQ_HOMALT=0;MALE_AN=2478;MALE_AC=0;MALE_AF=0;MALE_N_BI_GENOS=1239;MALE_N_HOMREF=1239;MALE_N_HET=0;MALE_N_HOMALT=0;MALE_FREQ_HOMREF=1;MALE_FREQ_HET=0;MALE_FREQ_HOMALT=0;FEMALE_AN=2444;FEMALE_AC=1;FEMALE_AF=0.000409;FEMALE_N_BI_GENOS=1222;FEMALE_N_HOMREF=1221;FEMALE_N_HET=1;FEMALE_N_HOMALT=0;FEMALE_FREQ_HOMREF=0.999182;FEMALE_FREQ_HET=0.000818331;FEMALE_FREQ_HOMALT=0
```

#### Expected behavior
The `END2` field should correspond to the end of the duplicated interval, in this case, `29481712`.

**Comment by epiercehoffman** [comment]
Thanks for flagging this inconsistency. We decided that since CHR2 and END2 cannot describe the full source interval, those fields should be removed instead from all CPX events. The information is retained in the CPX_INTERVALS field. Addressed by #583
