### ISSUE TITLE
Large CNV records missing depth genotypes causing failures in single sample pipeline

### ISSUE THREAD

**Issue by cwhelan** [broadinstitute/gatk-sv#400]
The single sample pipeline is failing on some samples with this error in CleanVcf:

```
Traceback (most recent call last):
  File "/opt/sv-pipeline/04_variant_resolution/scripts/clean_vcf_part5_update_records.py", line 181, in <module>
    main()
  File "/opt/sv-pipeline/04_variant_resolution/scripts/clean_vcf_part5_update_records.py", line 126, in main
    if not sample_obj['GQ'] is None and sample_obj['RD_CN'] >= 2:
TypeError: '>=' not supported between instances of 'NoneType' and 'int'
```

This is caused by CNVs greater than 5kb in size that are missing RD_CN depth genotypes.

**Comment by cwhelan** [comment]
I have a fix ready for this issue but wanted to create an issue for tracking.

**Comment by epiercehoffman** [comment]
Observed in one record in one cohort run with GATK-SV cohort mode as well, in a common 50kb DEL originating from Manta with PE, SR, and RD evidence.

**Comment by cwhelan** [comment]
I think this was fixed in https://github.com/broadinstitute/gatk-sv/pull/401. I may have been waiting for confirmation that it solved this issue for all users before closing. We should close if @epiercehoffman is no longer seeing the issue.

**Comment by epiercehoffman** [comment]
I believe this was a very rare issue. I haven't heard of it occurring since January. I would support closing this issue under the assumption it's been fixed, as the rarity of the error makes it hard to verify in practice. If it happens again we can open a new issue
