### ISSUE TITLE
Update Terra single sample pipeline workspace

### ISSUE THREAD

**Issue by cwhelan** [broadinstitute/gatk-sv#412]
The Terra single sample workspace has been broken due to being force-switched away from GATK docker image versions that dated prior to the log4j fixes. There also appear to be some issues that have arisen in the single sample workspace template files. The workflow should be updated to v0.26-beta and tested.

**Comment by epiercehoffman** [comment]
I think we can close this as the single-sample workspace has been updated and is currently at v0.26.9-beta
