### ISSUE TITLE
[Problem] PreprocessPESR.std_delly_vcf: []

### ISSUE THREAD

**Issue by NewOrange** [broadinstitute/gatk-sv#42]
### Instructions
I am very interesting to know more about GATKSVPipelineBatch.wdl.
I just plan to test GATKSVPipelineBatch.wdl with HG00096.final.bam and HG0129.final.bam.
During the test, I find an unusual condition.
The generated directory structure of **Module00c.call-PreprocessPESR.call-StandardizeVCFs** is just like below.
```xml
├── execution
│   ├── docker_cid
│   ├── glob-31de091d1940ddb276ce7b6086a74725
│   │   └── cromwell_glob_control_file
│   ├── glob-31de091d1940ddb276ce7b6086a74725.list
│   ├── manta.HG00096_unsorted.vcf
│   ├── manta.HG00129_unsorted.vcf
│   ├── rc
│   ├── script
│   ├── script.background
│   ├── script.submit
│   ├── std_000.manta.HG00096.vcf.gz
│   ├── std_001.manta.HG00129.vcf.gz
│   ├── stderr
│   ├── stderr.background
│   ├── stdout
│   └── stdout.background
├── inputs
│   ├── 1978095992
│   │   └── HG00129.manta.vcf.gz
│   ├── 745429519
│   │   └── contig.fai
│   └── -841028741
│       └── HG00096.manta.vcf.gz
└── tmp.92bdb17f
```
The related code is just like this.
```
  output {
    Array[File] std_vcf = glob("std_*.vcf.gz")
  }
```
Log output:
```
rocessPESR complete. Final Outputs:
  "PreprocessPESR.std_melt_vcf": null,
  "PreprocessPESR.std_wham_vcf": null,
  "PreprocessPESR.std_delly_vcf": [],
  "PreprocessPESR.std_manta_vcf": []
```
I used a previous version of the code for a test, only used one BAM file, did not encounter this problem.
Do you have any good suggestions for solving this problem?
***
Thank you very much.

**Comment by cwhelan** [comment]
What's the contents of `glob-31de091d1940ddb276ce7b6086a74725.list`? 

It looks like the task did successfully standardize the manta vcfs that were given to it as input, but cromwell didn't pick them up as inputs.

Did the entire workflow report any other errors in the logs?

**Comment by mwalker174** [comment]
This is unfortunately a result of the way Cromwell handles `glob` statements differently on local backends, which we aren't supporting. If anyone needs a workaround, they can always rewrite the WDL to avoid `glob`, ie by scattering over the VCF array and processing them individually.
