### ISSUE TITLE
Generate Terra workspace data tsv files from transposed tables

### ISSUE THREAD

**Issue by cwhelan** [broadinstitute/gatk-sv#432]
See the suggestions in https://github.com/broadinstitute/gatk-sv/pull/413

This would make it much easier to edit, view diffs, and track changes in git, which is currently very cumbersome with this two-row wide tsv format.

As noted on the ticket above @epiercehoffman has also entered a feature request for Terra to change the format it expects this file in: https://support.terra.bio/hc/en-us/community/posts/9319574881819-Make-workspace-tsv-format-edit-friendly-git-friendly

**Comment by shadizaheri** [comment]
This issue was resolved by merging [this pull request](https://github.com/broadinstitute/gatk-sv/pull/523).   Therefore, I go ahead and close this issue.
