### ISSUE TITLE
How much computing resources does we needs with Google Cloud ?

### ISSUE THREAD

**Issue by kt-hrd** [broadinstitute/gatk-sv#455]
Hi,

We are considering using GATKSVPipelineBacth.wdl of GATK-SV to analyze and process CRAM data for 100 people in our possession. 

When I ran a test with a sample of 5 persons, the 1TB of disk space I had prepared as a work area was full halfway through the process, and we were unable to process the data. 
At that time, we provided the VM resources on Google Cloud were 16 CPUs, 64GB memory, 200GB Boot disk and 1TB work disk. And the processing environment is based on CentOS7.9, using Singularity instead of Docker, and running on Cromwell.

How much computing resources on the Google Cloud are actually needed to process the data of 100 people?

**Comment by mwalker174** [comment]
Hi @kt-hrd, it sounds like you're trying to run on Cromwell configured with a local backend on your VM. This would likely take months to process your samples. 

We really recommend you instead use Google cloud as a backend as it will be able to take advantage of the Google Pipelines API to parallelize the workflow. There is documentation available for setting up GCS backends [here](https://cromwell.readthedocs.io/en/stable/backends/Google/).

**Comment by kt-hrd** [comment]
Hello @mwalker174, thank you so much for your reply.
We have just started processing 100 GATK-SV samples using Google's PAPI as per your recommendation.
We have also just found a description in Google's Cloud Life Science Tutorial regarding specific requirements for local computational resources. So we need a reasonable amount of computational resources on Google Cloud.
