### ISSUE TITLE
 GWAS-SVs pipeline Module 7 

### ISSUE THREAD

**Issue by fengzhm007** [broadinstitute/gatk-sv#460]
We encountered some troubles in the process of testing the GWAS-SVs pipeline with the GATK due to the lack of JSON files for module7. I wonder if you can share the JSON file in Module 7 (in development) of the SVs analysis (https://github.com/broadinstitute/gatk-sv#merge-batch-sites).  
Thank you very much for your attention and consideration.
Looking forward to your reply.

**Comment by mwalker174** [comment]
Hi @fengzhm007, we are currently working on filtering best practices and unfortunately can't provide much guidance on this yet. We hope to publish a working filtering method in the next few months.

**Comment by fengzhm007** [comment]
Thank you very much and look forward to the release soon
