### ISSUE TITLE
 does not have valid header (mode=`b'r'`) - is it VCF/BCF format?

### ISSUE THREAD

**Issue by yapingwu** [broadinstitute/gatk-sv#461]
Hello, 
    When I run the `svtk standardize` command, I get an error that the template file `GRCh37_template.vcf` is in the wrong format, how could I fix it?

>[E::bcf_hdr_parse_sample_line] Could not parse the "#CHROM.." line, either FORMAT is missing or spaces are present instead of tabs:
        #CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT
>
>Traceback (most recent call last):
  File "pysam/libcbcf.pyx", line 4341, in pysam.libcbcf.VariantFile.open
  File "pysam/libcbcf.pyx", line 2212, in pysam.libcbcf.makeVariantHeader
ValueError: cannot create VariantHeader
>
>During handling of the above exception, another exception occurred:
>
>Traceback (most recent call last):
  File "/root/software/anaconda3/envs/svtk/bin/svtk", line 67, in <module>
    main()
  File "/root/software/anaconda3/envs/svtk/bin/svtk", line 64, in main
    getattr(cli, command)(sys.argv[2:])
  File "/root/software/anaconda3/envs/svtk/lib/python3.9/site-packages/svtk/cli/standardize_vcf.py", line 77, in main
    template = VariantFile(template)
  File "pysam/libcbcf.pyx", line 4103, in pysam.libcbcf.VariantFile.__init__
  File "pysam/libcbcf.pyx", line 4343, in pysam.libcbcf.VariantFile.open
ValueError: file `b'/root/software/anaconda3/envs/svtk/lib/python3.9/site-packages/svtk/data/GRCh37_template.vcf'` does not have valid header (mode=`b'r'`) - is it VCF/BCF format?

![image](https://user-images.githubusercontent.com/16968238/203770883-a7b35d88-0975-429f-bbe3-3ccfbb02019c.png)

**Comment by mwalker174** [comment]
Hi @yapingwu, this does appear to be a bug. Can you try running the command using the `--contigs` argument and see if that resolves your issue? This should just be a file containing a list of the contig names like this for hg38:
```
chr1
chr2
chr3
chr4
chr5
chr6
chr7
chr8
chr9
chr10
chr11
chr12
chr13
chr14
chr15
chr16
chr17
chr18
chr19
chr20
chr21
chr22
chrX
chrY
```

**Comment by cuppacuppa** [comment]
@yapingwu Did you fix this error?
For my case, I referred other GitHub issue(https://github.com/gerstung-lab/deepSNV/issues/17).
I removed \tFORMAT from both of vcf header files, GRCh37_template.vcf and no_contigs_template.vcf.
Then, the svtk standardize works well.

**Comment by yapingwu** [comment]
@cuppacuppa Thank you for your kind reply. Your approach helped me address my problem.
