### ISSUE TITLE
Cohort mode GatherBatchEvidence workflow failing at BatchEvidenceMerging task/ MergeSREvidence subtask

### ISSUE THREAD

**Issue by riazgillani** [broadinstitute/gatk-sv#462]
### Affected module(s) or script(s)
Cohort mode GatherBatchEvidence workflow, BatchEvidenceMerging task/ MergeSREvidence subtask

### Affected version(s)
v0.25.1-beta

### Description 

The "Progress meter" in the MergeSREvidence subtask proceeds until arriving at a latter chromosome (anywhere from chr19 - chrX), and then the following error is produced: "htsjdk.samtools.util.RuntimeIOException: Write error; BinaryCodec in writemode". Tracing the error through shows that this is because there is "No space left on device."

I have attached the log.

I have 20 batches in my cohort, and this is mostly isolated to batches with higher WGD scores/ more SV calls deriving from a specific study (5 have failed). From my understanding of the wdl, the space could be modified with the runtime_attr_bem. However, I am unsure how to format/ update this optional input to evaluate this. I see it is a "WomCompositeType." Does it need to be a json, and if so, in what format?

#### Steps to reproduce

Rerunning the workflow without modification leads to failure.

#### Expected behavior

GatherBatchEvidence workflow should run to completion.

#### Actual behavior

Rerunning the workflow without modification leads to failure.
[MergeSREvidence_log_11_25_22.txt](https://github.com/broadinstitute/gatk-sv/files/10094014/MergeSREvidence_log_11_25_22.txt)

**Comment by mwalker174** [comment]
Hi @riazgillani, this is a common error message. "No space left on device" indicates more disk is needed. In your json you can override this like so:
```
"GatherBatchEvidence.runtime_attr_bem: {"disk_gb": "500"}
```
Looking over this workflow, I see we need to add runtime parameters for individual tasks, but this should still work for you. 

I'd also recommend looking at our [troubleshooting article](https://gatk.broadinstitute.org/hc/en-us/articles/5334566940699-Troubleshooting-GATK-SV), in particular [this video](https://www.youtube.com/watch?v=3UVV03H9p1w) which goes over more about how to debug these kinds of problems.

**Comment by riazgillani** [comment]
Thanks you, this was helpful and worked well. Thank you for the additional resources for troubleshooting.

Sincerely,
Riaz
