### ISSUE TITLE
OFC-driven suggestions for the STR workflow

### ISSUE THREAD

**Issue by VJalili** [broadinstitute/gatk-sv#469]

**Comment by Nehir291** [comment]
(1) Combine 4 sharded json files in workflow level

(2) From json to tsv conversion ADD --include-extra-expansion-hunter-fields
https://github.com/broadinstitute/str-analysis/blob/main/str_analysis/combine_str_json_to_tsv.py

(3) Zip the final output variant.tsv and alleles.tsv file

**Comment by VJalili** [comment]
Addressed in https://github.com/broadinstitute/gatk-sv/pull/516
