### ISSUE TITLE
Investigate upgrading Manta to v. 1.6.0

### ISSUE THREAD

**Issue by cwhelan** [broadinstitute/gatk-sv#47]
The release notes for v 1.6 (https://github.com/Illumina/manta/releases) say:

> This is a significant engineering update from the v1.5.1 release, in which the SV candidate generation step has been changed to a single multi-threaded process to improve task scheduling. This slightly improves average runtime and reduces runtime variability. With this update, support for job distribution over SGE is dropped.
> 
> Added
> Add configuration option to turn off the evidence signal filter during candidate generation (DRAGEN-1873)
> This enables very high sensitivity during high depth tumor-only calling
>
> Changed
> Change the SV candidate discovery and genotyping phase from a multi-process to a multi-thread design for better CPU utilization (MANTA-1521)
> As a result, runtime is faster and less variable than before.
> Runtime improvements vary by workload and server configuration, for typical WGS workloads on a modern server an improvement of ~5-10% may be expected, but improvements of up to 50% have been observed for cases where work previously was poorly distributed across processes.
> SGE support is removed with this change.
> Update htslib/samtools to 1.9 (MANTA-1483)

It sounds like we might get performance gains by upgrading (we currently use v1.5.0 in the pipeline).

**Comment by mwalker174** [comment]
Addressed in #601
