### ISSUE TITLE
Duplicated records in single sample pipeline output

### ISSUE THREAD

**Issue by cwhelan** [broadinstitute/gatk-sv#497]
There seem to be a number of duplicated records in the final VCF output from the single sample pipeline, particularly for CPX and INV events.

**Comment by cwhelan** [comment]
See for example `NA12878.chr1.final_cleanup_CPX_chr1_3` and `NA12878.chr1.final_cleanup_CPX_chr1_4` which are identical except for the record ID and the presence of the `BOTHISDES_SUPPORT` flag in one of the records. I think the flag being only in one record might be a quirk of how bcftools handles duplicate records.

**Comment by cwhelan** [comment]
Could be the same issues as https://github.com/broadinstitute/gatk-sv/issues/394

**Comment by mwalker174** [comment]
Yeah safe to assume that this was fixed in #576
