### ISSUE TITLE
Request for access to resources in resources_hg38.json

### ISSUE THREAD

**Issue by bioinfocure** [broadinstitute/gatk-sv#504]
Hi Team, 

Would it be possible to publicly share the resources in gs://gcp-public-data--broad-references/hg38/v0/sv-resources?

This will be helpful to access these resources or checking the format of the file contents such as "wham_include_list_bed_file", "primary_contigs_list", and potentially similar resources for other SV callers. I am trying to run some modules in the gatk-sv on an in-house system (not Terra).

Thanks!

----

**Comment by epiercehoffman** [comment]
Hi @bioinfocure, all of our resources files that are in a bucket with "public" in the name are shared publicly, so you should already have access to those files. You just need a Google account.

**Comment by bioinfocure** [comment]
Thank you @epiercehoffman, was able to access those files.

**Comment by epiercehoffman** [comment]
Google requires an account to interact with GCP so that they can charge for the service (the user or the bucket owner depending on whether the bucket is requester-pays)
