### ISSUE TITLE
GWAS-SVs pipeline Module 7

### ISSUE THREAD

**Issue by tanxiangyu** [broadinstitute/gatk-sv#512]
### Module(s) or script(s) involved
_GWAS-SVs pipeline Module 7

### Description 
We encountered some troubles in the process of testing the GWAS-SVs pipeline with the GATK due to the lack of JSON files for module7. I wonder if you can share the JSON file in Module 7 (in development) of the SVs analysis (https://github.com/broadinstitute/gatk-sv#merge-batch-sites).  
Thank you very much for your attention and consideration.
Looking forward to your reply.

**Comment by mwalker174** [comment]
Module07 is being deprecated. You should use `FilterGenotypes` instead (documentation forthcoming).
