### ISSUE TITLE
Request for Linting of build_docker.py

### ISSUE THREAD

**Issue by MattWellie** [broadinstitute/gatk-sv#513]
### Module(s) or script(s) involved

scripts/docker/build_docker.py

### Description

Could you please run Black/other code linter on this script? We are making some adjustments to suit our infrastructure and linting reformats this script enough that subsequent code review is challenging.

**Comment by VJalili** [comment]
@MattWellie All python scripts are linter-checked with [flake8](https://github.com/broadinstitute/gatk-sv/blob/main/tox.ini) to adhere with PEP8 guidelines. Are you seeing any specific issues with that script's linting?

**Comment by MattWellie** [comment]
Hi @VJalili, I confess I'm not super familiar with Flake8 and what it does/doesn't target. Your `tox.ini` is set to ignore `E501,W504,E722,F405`, and when I run `flake8 --isolated build_docker.py` E501 is the only error type that turns up which is consistent. 

When I run Pylint I see 104 linting failures across various types: `C0103, C0114, C0115, C0116, C0201, C0209, C0301, R0903, R0912, R0915, R1705, R1721, R1732, W0612, W1514`

When I run `black -l 200 --diff build_docker.py` (to prevent line length failures) there's a lot of lines that would be altered. 

I don't think this is an important issue, but I remain none the wiser about why Flake8 is seeing so few of these other types.
