### ISSUE TITLE
IntegrateGQ error in GenotypePESRPart2 in single sample pipeline

### ISSUE THREAD

**Issue by cwhelan** [broadinstitute/gatk-sv#520]
A user has run into an error in in the single sample pipeline, version 0.26.9-beta, involving a failure of one shard of the `IntegrateGQUnder5kb` task in `GenotypePESRPart2`. The task failed without any error messages written to the log file. This appears to be a rare issue as many other samples were processed successfully by the same version of the pipeline by the same user.

Further investigation shows that this is due to a very small shard on chromosome Y containing only one variant, which is causing grep statements within the script to fail to find any matches and return failure exit codes that break their bash pipelines.

**Comment by cwhelan** [comment]
The errors occur in `src/sv-pipeline/04_variant_resolution/scripts/IntegrateGQ.sh`

**Comment by mwalker174** [comment]
Addressed in #524
