### ISSUE TITLE
Add links to raw callers and SVAnnotate from README

### ISSUE THREAD

**Issue by epiercehoffman** [broadinstitute/gatk-sv#537]
Update README to link to each of the raw callers used by GATK-SV: Manta, Wham, MELT (already linked), cn.MOPS, and GATK-gCNV. Refer to this article for the links: https://gatk.broadinstitute.org/hc/en-us/articles/9022487952155-Structural-variant-SV-discovery

Also link to the GATK tool SVAnnotate (https://gatk.broadinstitute.org/hc/en-us/articles/13832752531355-SVAnnotate) under AnnotateVcf > functional annotation.

**Comment by kirtanav98** [comment]
Links added to SV callers in appropriate places.
