### ISSUE TITLE
Duplication of input data into GenotypeBatch crashes WF

### ISSUE THREAD

**Issue by MattWellie** [broadinstitute/gatk-sv#564]
### Affected module(s) or script(s)
GenotypeBatch workflow Stage 
- Specifically GenotypeDepthPart2
- More specifically here in [AddGenotypesOver5kb](https://github.com/broadinstitute/gatk-sv/blob/main/src/sv-pipeline/04_variant_resolution/scripts/add_genotypes.py#L197)
- Issue is with the input file generated by [IntegrateDepthGqOver5kb](https://github.com/broadinstitute/gatk-sv/blob/main/src/sv-pipeline/04_variant_resolution/scripts/IntegrateGQ_PESR.sh) which contains duplicate lines

### Affected version(s)
- [x] Latest public release version [v0.27.0]

Exact version of the codebase is the fork [here](https://github.com/populationgenomics/gatk-sv)

### Description 

Stacktrace in [add_genotypes.py](https://github.com/broadinstitute/gatk-sv/blob/main/src/sv-pipeline/04_variant_resolution/scripts/add_genotypes.py#L197) due to duplicated lines in the `RDTestGenotypeOver5kb.melted_genotypes` data file, so the PD.DataFrame representation can't be uniquely indexed.

```
Traceback (most recent call last):
  File "/opt/sv-pipeline/04_variant_resolution/scripts/add_genotypes.py", line 232, in <module>
    main()
  File "/opt/sv-pipeline/04_variant_resolution/scripts/add_genotypes.py", line 197, in main
    genotypes = genotypes.reindex(idx)
  File "/opt/conda/envs/gatk-sv/lib/python3.10/site-packages/pandas/util/_decorators.py", line 324, in wrapper
    return func(*args, **kwargs)
  File "/opt/conda/envs/gatk-sv/lib/python3.10/site-packages/pandas/core/frame.py", line 4804, in reindex
    return super().reindex(**kwargs)
  File "/opt/conda/envs/gatk-sv/lib/python3.10/site-packages/pandas/core/generic.py", line 4966, in reindex
    return self._reindex_axes(
  File "/opt/conda/envs/gatk-sv/lib/python3.10/site-packages/pandas/core/frame.py", line 4623, in _reindex_axes
    frame = frame._reindex_index(
  File "/opt/conda/envs/gatk-sv/lib/python3.10/site-packages/pandas/core/frame.py", line 4639, in _reindex_index
    new_index, indexer = self.index.reindex(
  File "/opt/conda/envs/gatk-sv/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 4205, in reindex
    raise ValueError("cannot handle a non-unique multi-index!")
ValueError: cannot handle a non-unique multi-index!
```

#### Steps to reproduce

I appreciate that this is not gonna be easy to repro anywhere else....

- Running in Cohort mode with 2 separate Cohorts - 119 samples each, no overlap between the two datasets (these could all fit into a single cohort for the batch workflow, but this is supposed to be a minimal test batch for combining results from two distinct pipeline runs).
- 2 Cohorts separately run through `GatherSampleEvidence` -> `FilterBatch`
- `MergeBatchSites` used to create union PESR & Depth VCFs from `FilterBatch` results of the two sub-batches
- Combined VCFs from `MergeBatchSites` used as input to `GenotypeBatch` (cohort_pesr_vcf/cohort_depth_vcf)
- During execution of `GenotypeBatch`, in both `GenotypeDepthPart2` and `GenotypePESRPart2` the workflow fails with the above StackTrace.

I've pulled out the relevant data files:

```
vcf = MakeSubsetVcfOver5kb.subset_vcf,
RD_melted_genotypes = RDTestGenotypeOver5kb.melted_genotypes,
RD_vargq = RDTestGenotypeOver5kb.varGQ
```

.. and I can recreate the same error locally - `genotype.indiv.depth.txt.gz` contains 511819 lines, only 465737 of which are unique. Running a cat|sort|uniq, 26902 total lines are repeated, 17312 are duplicated, and 9590 appear four times.

We've previously run the cohort workflow e2e on a single continuous cohort, and this is the first attempt after including `MergeBatchSites` in the middle of the pipeline. We might be able to stuff this up temporarily by adding a `genotypes = genotypes[~genotypes.index.duplicated()]` to retain only unique values in the DF prior to setting the index (tried locally, works fine), but I'm unsure if that might result in some fruity downstream behaviour.

I have no experience running this cross batch merging of component results, and I'm not sure why this rogue duplication/quadruplication has occurred. Any assistance in puzzling through this would be appreciated.

#### Expected behavior

¯\_(ツ)_/¯

#### Actual behavior

As described

**Comment by MattWellie** [comment]
Unsure if #522 is related

**Comment by MattWellie** [comment]
FYI @mwalker174 (bit of a throwback, I saw that you committed this script... 3 years ago)

I've proposed a remedy on our branch, but I would really appreciate your input to understand if this is caused by some underlying issue I haven't properly grokked.

https://github.com/populationgenomics/gatk-sv/pull/16

**Comment by epiercehoffman** [comment]
I have confirmed that we don't see duplicates in these files when running them on our end. 

After looking at the additional details in your linked PR in your fork, I see that there are duplicate variant IDs in RD_melted_genotypes for variants that have different breakpoints. That shouldn't be the case - the variant IDs should be unique variant identifiers. This makes me hesitate to simply apply `uniq` downstream, because it seems that you will lose some variants. Do you know how you ended up with duplicated variant IDs? Is there any chance your two batches were given the same batch ID, resulting in different variants from different batches being assigned the same variant ID?

**Comment by MattWellie** [comment]
Thanks for the reply @epiercehoffman. I'll try and track back from the files I currently have and see where that might have crept in. From your comment I'm taking that `seqr_depth_chr10_00000007` is a compound key of `batch_caller_chrom_incrementing-int`, so these should never clash for two different variants?

The batches are named by a hash of the samples they contain, so there shouldn't have been any possibility of crossover when merging the two files, but I'll dig in and double check

**Comment by MattWellie** [comment]
Self-reply, I assume you haven't seen my previous message yet 🙃 

I've had a little dig and I think you're right. The `seqr_` portion of the ID is supposed to be the ID specific to the batch, but I've conflated two things in the workflow setup, and that's being populated as the parent project the samples all belong to. This should hopefully be a simple fix.

**Comment by MattWellie** [comment]
Just checking in to say that this is all resolved, thanks @epiercehoffman !
