### ISSUE TITLE
whole exome data

### ISSUE THREAD

**Issue by sunliang3361** [broadinstitute/gatk-sv#57]
Very useful tool. Thank you. Could I ask if I can use this tool for my whole exome data?

**Comment by cwhelan** [comment]
This tool is designed for detecting germline variants in whole genome sequencing data. For calling copy number variation in whole exome data we recommend GATK gCNV: https://gatk.broadinstitute.org/hc/en-us/articles/360035531152--How-to-Call-common-and-rare-germline-copy-number-variants
