### ISSUE TITLE
Make LocalizeReads optional

### ISSUE THREAD

**Issue by mwalker174** [broadinstitute/gatk-sv#585]
The `LocalizeReads` task was recently introduced to `GatherSampleEvidence` to simplify cases for CRAMs sourced from requester-pays and multi-regional buckets. This simplified the code quite a bit. However, it would be beneficial in some cases to be able to bypass this for some cost and time savings. Adding an optional boolean skip this would be easy to implement.

**Comment by epiercehoffman** [comment]
Addressed in #620
