### ISSUE TITLE
Remove bash try-catch from GermlineCNVCallerCaseMode

### ISSUE THREAD

**Issue by TedBrookings** [broadinstitute/gatk-sv#59]
In GermlineCNVCase.wdl GermlineCNVCallerCaseMode implements a pseudo try-catch statement to overcome rare NaN errors. Development is ongoing to pull this retry into the GATK tool, and upon completion the existing task command block should be simplified.
- The try-catch block (actually two `{}` command blocks separated by `||`) should be removed.
- The function `run_gcnv_case()` should be simply inlined as code to be executed.
- The function `get_seeded_random()` should be removed.

**Comment by mwalker174** [comment]
This was addressed in GATK
