### ISSUE TITLE
FilterGenotypes relies on unavailable tool

### ISSUE THREAD

**Issue by MattWellie** [broadinstitute/gatk-sv#598]
[see line](https://github.com/broadinstitute/gatk-sv/blob/2c97aad67bd5e7fb0c7632fc0ed632444e6f624d/wdl/RecalibrateGq.wdl#L92)

FilterGenotypes.wdl -> RecalibrateGq.wdl

The RecalibrateGqTask contains a usage of `XGBoostMinGqVariantFilter`. The only reference to that tool in the GATK suite is [this un-merged PR](https://github.com/broadinstitute/gatk/pull/7705), and it is currently unavailable in the `gatk_docker` image referenced in the config for this repository. 

Could you please clarify if this tool will become available, or if an alternative filtering method is available?

**Comment by epiercehoffman** [comment]
The downstream filtering steps are still in development. Further documentation is forthcoming once they are finalized. However, they can still be used in the meantime.

The docker used for RecalibrateGq, `gq_recalibrator_docker`, is defined in the [dockers.json](https://github.com/broadinstitute/gatk-sv/blob/main/inputs/values/dockers.json#L33C30-L33C112) as `us.gcr.io/broad-dsde-methods/markw/gatk:mw-tb-form-sv-filter-training-data-899360a`. You can see which docker is used by looking at the input JSON template provided for FilterGenotypes.wdl [here](https://github.com/broadinstitute/gatk-sv/blob/main/inputs/templates/test/FilterGenotypes/FilterGenotypes.fixed_cutoffs.json.tmpl#L39).
