### ISSUE TITLE
WhamG memory issues hard to treat

### ISSUE THREAD

**Issue by MattWellie** [broadinstitute/gatk-sv#624]
https://github.com/broadinstitute/gatk-sv/blob/dc92e9f4bc46a1ab19459b515c24c9747a73a967/wdl/Whamg.wdl#L220

This value is fixed at 0.0 and can't be edited. This is later used in a calculation, but it the result will always be 0. 

https://github.com/broadinstitute/gatk-sv/blob/main/wdl/Whamg.wdl#L225-L229

We're running into some WhamG memory issues on some samples, but we can't bump the memory on a per-sample basis without handling `pf_reads_improper_pairs` & `pct_exc_total`; I've no concept of what reasonable values for these would be. The `mem_per_bam_size * bam_size + mem_bam_offset` calculation would be easier to influence, but due to the fixed `0.0` value it can't be edited.

**Comment by mwalker174** [comment]
Hi @MattWellie,

You should be able to override the memory setting using `runtime_attr_wham` in `GatherSampleEvidence`, e.g. `{'mem_gb': 16}`.

**Comment by MattWellie** [comment]
Chained attribute override
