### ISSUE TITLE
SplitVariants task in TasksGenotypeBatch.wdl not compatible with downstream analysis

### ISSUE THREAD

**Issue by leqi0001** [broadinstitute/gatk-sv#642]
## Bug Report

I'm testing this on local HPCs, not on Terra. However I don't see how that makes a difference.

### Affected module(s) or script(s)
SplitVariants task in TasksGenotypeBatch.wdl (310eb7b28cf87a984b8d14afe2874ec14a052dab)

### Description 
The SplitVariants task used to have some lines to switch columns 5 and 6 of the bed file output, which is read in downstream tasks of TrainRDGenotyping.GenotypePESR. This causes the TrainRDGenotyping.GenotypePESR to error out reporting. 

Error: WARNING: Incorrect CNV type specified
1: stop("WARNING: Incorrect CNV type specified")

using the following code from previous wdl scripts solves the problem.

 svtk vcf2bed ~{vcf} stdout \
      | awk -v OFS="\t" '(($5=="DEL" || $5=="DUP") && $3-$2>=5000) {print $1, $2, $3, $4, $6, $5}' \
      | split --additional-suffix ".bed" -l ~{n_per_split} -a 6 - gt5kb.
    svtk vcf2bed ~{vcf} stdout \
      | awk -v OFS="\t" '(($5=="DEL" || $5=="DUP") && $3-$2<5000) {print $1, $2, $3, $4, $6, $5}' \
      | split --additional-suffix ".bed" -l ~{n_per_split} -a 6 - lt5kb.
    if [ ~{generate_bca} == "true" ]; then
      svtk vcf2bed ~{vcf} stdout \
        | awk -v OFS="\t" '($5!="DEL" && $5!="DUP" && $5!="INS") {print $1, $2, $3, $4, $6, $5}' \
        | split --additional-suffix ".bed" -l ~{n_per_split} -a 6 - bca.
      svtk vcf2bed ~{vcf} stdout \
        | awk -v OFS="\t" '($5=="INS") {print $1, $2, $3, $4, $6, $5}' \
        | split --additional-suffix ".bed" -l ~{n_per_split} -a 6 - ins.
    fi

#### Expected behavior
column 6 of the output bed file should be types of CNVs and column 5 should be sample names, but it's the other way around at the moment.

**Comment by epiercehoffman** [comment]
Thanks for bringing this to our attention. I was able to reproduce this error and the team is working on getting a fix in shortly.

**Comment by kirtanav98** [comment]
This issue was addressed [here](https://github.com/broadinstitute/gatk-sv/pull/650)
