### ISSUE TITLE
MEIs in SplitVariants

### ISSUE THREAD

**Issue by epiercehoffman** [broadinstitute/gatk-sv#649]
svtk vcf2bed uses the ALT field to produce the `svtype` column in the output BED file. This means that the `svtype` column includes BND alt alleles and values like INS:ME for MEIs. However, the [current](https://github.com/broadinstitute/gatk-sv/blob/0cad1662db0522dee17ae6d874a51cab6b739cae/src/sv-pipeline/04_variant_resolution/scripts/split_variants.py#L20) and [previous](https://github.com/broadinstitute/gatk-sv/blob/v0.28.4-beta/wdl/TasksGenotypeBatch.wdl#L44) SplitVariants tasks  in GenotypeBatch match exactly on the string "INS" when creating insertion-specific BED files, so the MEIs get grouped with BCAs instead. We should evaluate the impact of this on genotyping and whether MEIs should be grouped with other INS events instead.

**Comment by jingydz** [comment]
It appears that the file named 'svtypes.txt' can be defined by yourself.

**Comment by epiercehoffman** [comment]
Addressed in #687
