### ISSUE TITLE
gCNV JointSegmentation fails on sex aneuploidies

### ISSUE THREAD

**Issue by MattWellie** [broadinstitute/gatk-sv#677]
This is more of a process question, and may not be the correct forum...

Looking through the WDLs here I'm not even sure the tool is involved in this workflow...

Related to https://github.com/broadinstitute/gatk/issues/8834

We're hitting issues when assembling a gCNV joint callset using JointSegmentation, as the tool doesn't support sex aneuploidies. Can we check if you use this tool, and if so, whether you deal with sex aneuploidy through sample removal, or meddling with the variants/calls somehow to create data in a compatible format?

**Comment by epiercehoffman** [comment]
We do use gCNV, but we don’t appear to use the joint segmentation tool. We perform our own joint genotyping after using gCNV for depth CNV discovery. So questions related to the joint segmentation are probably best answered by the GATK team - I hope you get some help with the issue you opened in the gatk repo!

As you can see in our [README](https://github.com/broadinstitute/gatk-sv?tab=readme-ov-file#ped-file-format), we retain samples with sex chromosome aneuploidies but set the sex=0 in the PED file, which is input to a later step in the pipeline that removes calls on allosomes for those samples.

**Comment by mwalker174** [comment]
Closing, as JointGermlineCNVSegmentation isn't used in gatk-sv
