### ISSUE TITLE
MELT Dockerfile

### ISSUE THREAD

**Issue by c2997108** [broadinstitute/gatk-sv#697]
The MELT Dockerfile indicates that I need to use sv-base:latest, but it doesn't seem to be registered on dockerhub. 
Which image should I use?

**Comment by mwalker174** [comment]
The `sv_base_docker` in [dockers.json](https://github.com/broadinstitute/gatk-sv/blob/main/inputs/values/dockers.json) should work. Currently that would be `us.gcr.io/broad-dsde-methods/gatk-sv/sv-base:2024-01-24-v0.28.4-beta-9debd6d7`
