### ISSUE TITLE
Deprecate cloud_env JSON / google_cloud.my_project.json for building inputs

### ISSUE THREAD

**Issue by epiercehoffman** [broadinstitute/gatk-sv#709]
The cloud_env JSON (inputs/values/google_cloud.my_project.json) was formerly used to provide a google or Terra project ID for building inputs. This is no longer needed for any of the default input templates so this JSON can be deprecated. This will involve removing reliance on it from the scripts to build inputs and the launch_wdl.sh script, as well as removing references to it from the documentation.

**Comment by kjaisingh** [comment]
Search for the following:
- _google_project_id_
- _terra_billing_project_id_
- _google_cloud.json_
- _google_cloud.*.json_
