### ISSUE TITLE
Cannot find generate_rdtest_bed.R in the gatksv/sv-pipeline-qc docker environment

### ISSUE THREAD

**Issue by fengcong3** [broadinstitute/gatk-sv#71]
In `Module03Qc.wdl`,

> task VcfExternalBenchmark_to_Rdtest {
>   input {
>     File vcf_stats
>     File comparator
>     String sv_pipeline_qc_docker
>     RuntimeAttr? runtime_attr_override
>   }
>   
> 
>   Float input_size = 2 * size(vcf_stats, "GiB")
>   Float compression_factor = 5.0
>   Float base_disk_gb = 5.0
>   Float base_mem_gb = 2.0
>   RuntimeAttr runtime_default = object {
>     mem_gb: base_mem_gb + compression_factor * input_size,
>     disk_gb: ceil(base_disk_gb + input_size * (2.0 + 2.0 * compression_factor)),
>     cpu_cores: 1,
>     preemptible_tries: 3,
>     max_retries: 1,
>     boot_disk_gb: 10
>   }
>   RuntimeAttr runtime_override = select_first([runtime_attr_override, runtime_default])
>   runtime {
>     memory: "~{select_first([runtime_override.mem_gb, runtime_default.mem_gb])} GiB"
>     disks: "local-disk ~{select_first([runtime_override.disk_gb, runtime_default.disk_gb])} HDD"
>     cpu: select_first([runtime_override.cpu_cores, runtime_default.cpu_cores])
>     preemptible: select_first([runtime_override.preemptible_tries, runtime_default.preemptible_tries])
>     maxRetries: select_first([runtime_override.max_retries, runtime_default.max_retries])
>     docker: sv_pipeline_qc_docker
>     bootDiskSizeGb: select_first([runtime_override.boot_disk_gb, runtime_default.boot_disk_gb])
>   }
> 
>   command <<<
>     set -eu -o pipefail    
>     # Run benchmarking script
>     /opt/sv-pipeline/scripts/vcf_qc/compare_callsets_V2.sh \
>       -O ~{vcf_stats}.SENS.bed
>       ~{vcf_stats} \
>       ~{comparator} 
>     /opt/sv-pipeline/scripts/vcf_qc/compare_callsets_V2.sh \
>       -O ~{vcf_stats}.SPEC.bed
>       ~{comparator} \
>       ~{vcf_stats} 
>     awk '{if ($8=="NO_OVR" && $9=="NO_OVR" && $3-$2>5000) print}' \
>     ~{vcf_stats}.SENS.bed \
>     | awk '{if ($5=="DEL" || $5=="DEL_ALU" || $5=="DEL_HERV" || $5=="DEL_LINE1" || $5=="DEL_SVA" || $5=="DUP") print}' \
>     > ~{vcf_stats}.missed.large_cnv.bed
>     awk '{if ($8=="NO_OVR" && $9=="NO_OVR" && $3-$2>5000) print}' \
>     ~{vcf_stats}.SPEC.bed \
>     | awk '{if ($5=="DEL" || $5=="DEL_ALU" || $5=="DEL_HERV" || $5=="DEL_LINE1" || $5=="DEL_SVA" || $5=="DUP") print}' \
>     > ~{vcf_stats}.newUniq.large_cnv.bed
>     Rscript generate_rdtest_bed.R \
>     -r ~{vcf_stats}.missed.large_cnv.bed \
>     -b  ~{comparator} \
>     -o ~{vcf_stats}.missed.large_cnv.rdtest.bed 
>     Rscript generate_rdtest_bed.R \
>     -r ~{vcf_stats}.newUniq.large_cnv.bed \
>     -b ~{vcf_stats} \
>     -o ~{vcf_stats}.newUniq.large_cnv.rdtest.bed 
>     # Prep outputs
>   >>>
> 
>   output {
>     File sens = "\~{vcf_stats}.SENS.bed"
>     File spec = "\~{vcf_stats}.SPEC.bed"
>     File rdtest_missed = "\~{vcf_stats}.missed.large_cnv.rdtest.bed"
>     File rdtest_newunique = "\~{vcf_stats}.newUniq.large_cnv.rdtest.bed "
>     
>   }
> }

`generate_rdtest_bed.R` is used in the code, but I did not find this R script in the latest docker image (_gatksv/sv-pipeline-qc:b3af2e3_ and _epiercehoffman/sv-pipeline-qc:eph_03qc_variables-e597d85_). Could anyone provide it?

Thanks.

**Comment by mwalker174** [comment]
Thank you for reporting this. I can't seem to find this script in our version history. Interestingly the `VcfExternalBenchmark_to_Rdtest` doesn't seem to be incorporated in the final tarball and should probably be removed.

**Comment by mwalker174** [comment]
Task is removed
