### ISSUE TITLE
1000G callset?

### ISSUE THREAD

**Issue by jaredo** [broadinstitute/gatk-sv#73]
Hi there,

Has the pipeline been run on the high coverage 1000G data released by NYGC? I'd love to get my hands on the callset if available!

Thanks,

Jared

**Comment by xuefzhao** [comment]
Hi,  thanks for your interest! We are preparing the manuscript on these samples, where the callset will be delivered together. Paper will come soon !

**Comment by jaredo** [comment]
Thanks, looking forward to it.
