### ISSUE TITLE
Reconfigure external benchmarking datasets for automatic QC in Module05_06

### ISSUE THREAD

**Issue by RCollins13** [broadinstitute/gatk-sv#76]
Currently, Module05_06 takes the following as optional inputs:
```
Array[File]? thousand_genomes_tarballs
Array[File]? hgsv_tarballs
Array[File]? asc_tarballs
File? sanders_2015_tarball
File? collins_2017_tarball
File? werling_2018_tarball
```

These files are used to ensure appropriate calibration of allele frequencies, etc., and (where applicable) to directly compare sensitivity and PPV per sample vs. previous callsets.

Not an urgent request, but we should eventually reconfigure these inputs to flexibly accept any number of cohort-level and sample-level tarballs if any external benchmarking datasets are desired. For example, I would imagine gnomAD & 1kG being the default cohort-level benchmarking datasets, with a default of zero per-sample benchmarking datasets (although either of these could be overridden by the user depending on their cohort/study design, etc).

Happy to discuss in more detail if/when anyone reworks the standard QC subroutines in Module05_06

**Comment by mwalker174** [comment]
Addressed in #388
