### ISSUE TITLE
Avoid repeated calculation

### ISSUE THREAD

**Issue by henriqueribeiro** [broadinstitute/gatk-sv#85]
Hey,

I was wondering if in the BatchEvidenceMerging.wdl, on the MergeEvidenceFilesByContig task, it wouldn't make sense to avoid this calculation:
https://github.com/broadinstitute/gatk-sv/blob/162882bedb0698ed9bba3cb97c87f86632e890f2/wdl/BatchEvidenceMerging.wdl#L216

Since this task will be scattered, each one of those will calculate it when the value is the same for all of them. So, what do you think to calculate this value outside of the scatter and send it as input?

**Comment by mwalker174** [comment]
Thanks for your suggestion, @henriqueribeiro. It certainly would be beneficial to avoid scattering the `size()` call in particular, unless Cromwell doesn't have a mechanism for caching that (it does, for example, cache file hashes across tasks).

**Comment by henriqueribeiro** [comment]
thanks for the feedback @mwalker174. Are you talking about setting `system.file-hash-cache` to `true`? I never tried this configuration

**Comment by mwalker174** [comment]
@henriqueribeiro Yes it is good to turn it on, as it improves caching performance substantially particularly when you have a large array input within a scatter (e.g. our GermlineCNV workflow).

**Comment by henriqueribeiro** [comment]
Nice! I will turn it on. Nevertheless, do you think it makes sense to do the `disk_size_gb` outside the scatter? If you want I can do that change and create a PR

**Comment by mwalker174** [comment]
I think we can leave this one as-is. We have run this workflow on a 280-batch cohort without issue, and it is a bit more readable/consistent to have the disk calculation inside the task.
