### ISSUE TITLE
Error running tasks04.CountPE

### ISSUE THREAD

**Issue by henriqueribeiro** [broadinstitute/gatk-sv#87]
I'm running `GATKSVPipelineSingleSample.wdl` and I'm facing this error in Module04:

> A USER ERROR has occurred: An index is required but was not found for file /tmp/scratch/xxxxx-gwf-core/cromwell-execution/GATKSVPipelineSingleSample/4e9e57d2-48ef-4b52-9cb8-5324c64cfddc/call-Module00c/Module00c/d2cdda29-616b-44ea-8e1a-9225c05e73da/call-EvidenceMerging/EvidenceMerging/c4f03868-e71b-452b-83f2-edf54f0f580b/call-MergePEShards/test_na12878.PE.txt.gz. Support for unindexed block-compressed files has been temporarily disabled. Try running IndexFeatureFile on the input.

However, Module00c is also outputting `test_na12878.PE.txt.gz.tbi` but is not being fed to this task. Is this correct?

Thanks in advance

**Comment by mwalker174** [comment]
Hi @henriqueribeiro,

On GCP, we use GATK to stream PE data directly from the bucket to avoid localizing the entire file. This won't work with any other backend (eg local or AWS). If you are running with another backend, you should just need to add the index as an input so that it localizes.

**Comment by henriqueribeiro** [comment]
it makes sense. I will add it to the wdl file. After testing it, does it make sense to do a pull request?

**Comment by mwalker174** [comment]
@henriqueribeiro Yes a PR would be helpful. If you could find instances where `localization_optional` is used and add index inputs?

**Comment by henriqueribeiro** [comment]
Just did a pull request. Can you please review it?
Thanks a lot

**Comment by henriqueribeiro** [comment]
solved
