### ISSUE TITLE
Evaluate removing/updating filters from module 05/06

### ISSUE THREAD

**Issue by cwhelan** [broadinstitute/gatk-sv#97]
The single sample pipeline currently removes three filters that module 0506 applies to sites and turns them into INFO flags: `BOTHSIDES_SUPPORT`, `HIGH_SR_BACKGROUND`, and `PESR_GT_OVERDISPERSION`.

`BOTHSIDES_SUPPORT` should probably not be a filter in the first place; I don't think it is meant to actually filter low quality variants out.

After evaluating `HIGH_SR_BACKGROUND` and `PESR_GT_OVERDISPERSION` variants in single sample pipeline output and comparing them to PacBio calls, we decided to remove these as a hard filter. We do this in a postprocessing step after 05/06 has run. However, it may be that these filters are still useful in some contexts -- for example, in a cohort mode run where the samples are more diverse in terms of technical artifacts or quality. 

We should evaluate whether these filters are actually useful in the cohort mode pipeline, and if they're not, remove them from module 05/06 (and get rid of the logic to reset them in the single sample pipeline).

**Comment by mwalker174** [comment]
Note that these filters were moved to the INFO column in #554 for joint calling. They are now used in `FilterGenotypes` and probably carry some useful signal, although we haven't done a rigorous analysis. I'm going to close this ticket for now.
