### ISSUE TITLE
BND type missing functional annotations

### ISSUE THREAD

**Issue by alsanju** [broadinstitute/gatk-sv#99]
### Affected module(s) or script(s)
Module 08 - Annotation

### Description 
Functional annotations currently missing for BND types after running GATK-SV cohort mode. `PROTEIN_CODING_`, `LINCRNA_` and `NONCODING_` fields are not being annotated, even if a BND overlaps a region present in these  annotation sources.

#### Actual behavior
An example is the following BND, located in an intron of the protein coding gene MED13L (NM_015335.4). The post-annotation entry in the VCF is:

```
CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO
chr12	116224357	.	N	<BND>	1	UNRESOLVED	END=116224357;SVTYPE=BND;CHR2=chr12;STRANDS=+-;SVLEN=13306;ALGORITHMS=manta;EVIDENCE=PE,SR;UNRESOLVED_TYPE=SINGLE_ENDER_+-;AN=1428;AC=1;AF=0.0007;N_BI_GENOS=714;N_HOMREF=713;N_HET=1;N_HOMALT=0;FREQ_HOMREF=0.998599;FREQ_HET=0.00140056;FREQ_HOMALT=0;MALE_AN=772;MALE_AC=1;MALE_AF=0.001295;MALE_N_BI_GENOS=386;MALE_N_HOMREF=385;MALE_N_HET=1;MALE_N_HOMALT=0;MALE_FREQ_HOMREF=0.997409;MALE_FREQ_HET=0.00259067;MALE_FREQ_HOMALT=0;FEMALE_AN=656;FEMALE_AC=0;FEMALE_AF=0;FEMALE_N_BI_GENOS=328;FEMALE_N_HOMREF=328;FEMALE_N_HET=0;FEMALE_N_HOMALT=0;FEMALE_FREQ_HOMREF=1;FEMALE_FREQ_HET=0;FEMALE_FREQ_HOMALT=0
```

Entry for the gene that should’ve been annotated in the `AnnotateVcf.protein_coding_gtf` file used:

```
chr12	HAVANA	gene	115953872	116277719	.	-	.	gene_id "ENSG00000123066.8"; gene_type "protein_coding"; gene_name "MED13L"; level 1; tag "ncRNA_host"; tag "overlapping_locus"; havana_gene "OTTHUMG00000169404.9"
```

#### Expected behavior
MED13L should be annotated as `PROTEIN_CODING_INTRONIC`.

#### Comment 
It might be good to consider having a `PROTEIN_CODING_BND_SPAN` field for intra-chromosomal events such as this one.

**Comment by mwalker174** [comment]
@epiercehoffman Will this change with the upcoming tool?

**Comment by mwalker174** [comment]
Consolidating with #100
